### ISSUE TITLE
RuntimeError: Attempted to use a closed Session.

### ISSUE THREAD

**Issue by ViVi0122** [webrtcHacks/tfObjWebrtc#3]
I try to running the hard way, In 2.1 Turn the Demo code into a service when i run the object_detection_api_test.py it give a error i can fix it.
This is my error and tensorflow version.
Version:
    Tensorflow:1.5.0
    python:3.6.3
    protoc:2.6

Error:
   Traceback (most recent call last):
      File "object_detection_api_test.py", line 11, in <module>
          response = object_detection_api.get_objects(image)
      File "/home/hallen/models/research/object_detection/tfweb/object_detection_api.py", line 90, in 
      get_objects
          feed_dict={image_tensor: image_np_expanded})
      File "/home/hallen/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 
      900, in run
          run_metadata_ptr)
      File "/home/hallen/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 
      1058, in _run
          raise RuntimeError('Attempted to use a closed Session.')
      RuntimeError: Attempted to use a closed Session.

**Comment by chadwallacehart** [comment]
Did the Part  1 code work ok?

**Comment by ViVi0122** [comment]
Yes,it work

**Comment by AmitKKhanchandani** [comment]
@ViVi0122 you were able to run the complete project?

What's the status now?

**Comment by ViVi0122** [comment]
@AmitKKhanchandani  I have this error

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/Flask-1.0.2-py3.6.egg/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/dist-packages/Flask-1.0.2-py3.6.egg/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/Flask-1.0.2-py3.6.egg/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/Flask-1.0.2-py3.6.egg/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/Flask-1.0.2-py3.6.egg/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/Flask-1.0.2-py3.6.egg/flask/app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.6/dist-packages/Flask-1.0.2-py3.6.egg/flask/app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.6/dist-packages/Flask-1.0.2-py3.6.egg/flask/app.py", line 1982, in make_response
    reraise(TypeError, new_error, sys.exc_info()[2])
  File "/usr/local/lib/python3.6/dist-packages/Flask-1.0.2-py3.6.egg/flask/_compat.py", line 34, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/dist-packages/Flask-1.0.2-py3.6.egg/flask/app.py", line 1974, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "/home/hallen/.local/lib/python3.6/site-packages/werkzeug/wrappers.py", line 921, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "/home/hallen/.local/lib/python3.6/site-packages/werkzeug/wrappers.py", line 59, in _run_wsgi_app
    return _run_wsgi_app(*args)
  File "/home/hallen/.local/lib/python3.6/site-packages/werkzeug/test.py", line 923, in run_wsgi_app
    app_rv = app(environ, start_response)
TypeError: 'RuntimeError' object is not callable
The view function did not return a valid response. The return type must be a string, tuple, Response instance, or WSGI callable, but it was a RuntimeError.

**Comment by AmitKKhanchandani** [comment]
@ViVi0122 I'm not getting this kind of error, did you modify anything in the source code?

I did get the RuntimeError: Attempted to use a closed Session Error, but I revert tensorflow back to 1.4.0 version and got a different kind of issue which is [TypeError: 1 is not JSON serializable](https://github.com/webrtcHacks/tfObjWebrtc/issues/5)

**Comment by jeroenboeye** [comment]
Hi @AmitKKhanchandani,

I ran into the same issue and was able to fix it. The reason is that a numpy integer type is not serializable (see this stackoverflow question: https://stackoverflow.com/questions/11942364).

The fix that worked for me is to adjust the `object_detection_api.py` file so that

> `item.numObjects = obj_above_thresh` 

becomes
> `item.numObjects = int(obj_above_thresh)`
