### ISSUE TITLE
Type error

### ISSUE THREAD

**Issue by Clamps251** [webrtcHacks/tfObjWebrtc#4]
Hi,

I am getting the following error when i navigate to either /local or /video:

server.py", line 61, in image print('POST /image error: %e' % e)
TypeError: must be real number, not RuntimeError

Has anyone come across this issue?

Thanks for any help :)

**Comment by chadwallacehart** [comment]
I would try changing that line to just `print(e)` and see what happens.

**Comment by Clamps251** [comment]
Hi,

Thanks for getting back to me. I have tried it and now it says typeerror: a float is required.

**Comment by AmitKKhanchandani** [comment]
Any Solution to this?

**Comment by AmitKKhanchandani** [comment]
@chadwallacehart 
> I would try changing that line to just `print(e)` and see what happens.

```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\flask\app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\flask\app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\flask\app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\laragon\www\temp\tfObjWebrtc\server.py", line 61, in image
    print('POST /image error: %e' % e)
TypeError: a float is required
```

any idea how to fix this?

Specs:
Tensorflow: 1.12.0
Python 3.5 using Anaconda

**Comment by chadwallacehart** [comment]
Sorry, I haven't worked with this project for a while. 

I think that `%e` should be a `%s` on line 61 or it should be changed to `print('POST /image error: ', e)` . However, if that is occurring you are still getting an exception so there is still some issue. At least if you can see the error that might tell you what to look at next.

I guess you _are not_ running this inside the docker container?
`docker run -it -p 5000:5000 chadhart/tensorflow-object-detection:runserver`
