### ISSUE TITLE
TypeError: 1 is not JSON serializable

### ISSUE THREAD

**Issue by AmitKKhanchandani** [webrtcHacks/tfObjWebrtc#5]
Specs:
Tensorflow 1.4.0 | (1.12.0 is the latest version available at this time, but revert back to 1.4.0 for this project)
Python 3.5
OS: Windows 8.1

I'm testing the Live Local Webcam (http://localhost:5000/local) page.

in the Chrome Debug Window I get the following errors:

http://localhost:5000/image : returns the 500 Internal Server Error.

```
builtins.TypeError
TypeError: 1 is not JSON serializable
```

Error Log from the command prompt:
```

127.0.0.1 - - [14/Dec/2018 16:25:09] "GET /local HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2018 16:25:10] "GET /static/local.js HTTP/1.1" 200 -
127.0.0.1 - - [14/Dec/2018 16:25:10] "GET /static/objDetect.js HTTP/1.1" 200 -
detected 1 objects in image above a 0.5 score
output>
[<object_detection_api.Object object at 0x000000F129B39F28>]
 object person - score: 0.8031016, coordinates: [0.05477852 0.25362617 0.9905252
  0.9987053 ]
output of the object detection api sample
127.0.0.1 - - [14/Dec/2018 16:25:34] "POST /image HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\t14\lib\site-packages\flask\app.py", line
2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\ProgramData\Anaconda3\envs\t14\lib\site-packages\flask\app.py", line
2295, in wsgi_app
    response = self.handle_exception(e)
  File "C:\ProgramData\Anaconda3\envs\t14\lib\site-packages\flask\app.py", line
1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\ProgramData\Anaconda3\envs\t14\lib\site-packages\flask\_compat.py", l
ine 35, in reraise
    raise value
  File "C:\ProgramData\Anaconda3\envs\t14\lib\site-packages\flask\app.py", line
2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\ProgramData\Anaconda3\envs\t14\lib\site-packages\flask\app.py", line
1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\ProgramData\Anaconda3\envs\t14\lib\site-packages\flask\app.py", line
1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\ProgramData\Anaconda3\envs\t14\lib\site-packages\flask\_compat.py", l
ine 35, in reraise
    raise value
  File "C:\ProgramData\Anaconda3\envs\t14\lib\site-packages\flask\app.py", line
1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\ProgramData\Anaconda3\envs\t14\lib\site-packages\flask\app.py", line
1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\laragon\www\temp\tfObjWebrtc\server.py", line 57, in image
    objects = object_detection_api.get_objects(image_object)
  File "C:\laragon\www\temp\tfObjWebrtc\object_detection_api.py", line 131, in g
et_objects
    outputJson = json.dumps([ob.__dict__ for ob in output])
  File "C:\ProgramData\Anaconda3\envs\t14\lib\json\__init__.py", line 230, in du
mps
    return _default_encoder.encode(obj)
  File "C:\ProgramData\Anaconda3\envs\t14\lib\json\encoder.py", line 198, in enc
ode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\ProgramData\Anaconda3\envs\t14\lib\json\encoder.py", line 256, in ite
rencode
    return _iterencode(o, 0)
  File "C:\ProgramData\Anaconda3\envs\t14\lib\json\encoder.py", line 179, in def
ault
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: 1 is not JSON serializable
```

How can i fix this out?

Looking forward to your solution

**Comment by jeroenboeye** [comment]
Hi @AmitKKhanchandani,

I ran into the same issue and was able to fix it. The reason is that a numpy integer type is not serializable (see this stackoverflow question: https://stackoverflow.com/questions/11942364).

The fix that worked for me is to adjust the `object_detection_api.py` file so that

> `item.numObjects = obj_above_thresh` 

becomes
> `item.numObjects = int(obj_above_thresh)`
